os: osx
osx_image: xcode15.0
language: swift
script: xcodebuild clean build test -project /Users/rohiguera/Desktop/Xcode/0_essential_developer_iOS/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
