name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test CI scheme using Mac platform
    runs-on: macos-latest

    steps:
      - name: Test
        run: |
          xcodebuild clean build test -project rhigueraa/essentialproject/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
